name: Add information to Bash script

on:
  push:
    paths:
      - '*.sh'

jobs:
  debug_variables:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Variables
        run: |
          echo "github.workspace: ${{ github.workspace }}"
          echo "github.event_path: ${{ github.event_path }}"
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.repository: ${{ github.repository }}"
          echo "github.ref: ${{ github.ref }}"
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "github.base_ref: ${{ github.base_ref }}"
          echo "github.sha: ${{ github.sha }}"
          echo "github.actor: ${{ github.actor }}"
          echo "github.job: ${{ github.job }}"
          echo "github.run_id: ${{ github.run_id }}"
          echo "github.run_number: ${{ github.run_number }}"
          echo "github.action: ${{ github.action }}"
          echo "github.api_url: ${{ github.api_url }}"
          echo "github.graphql_url: ${{ github.graphql_url }}"
          echo "github.workspace_slug: ${{ github.workspace_slug }}"
